---
collections:
  - name: community.general
    type: galaxy
    version: 12.1.0

  - name: community.docker
    type: galaxy
    version: 5.0.4

  - name: ansible.posix
    type: galaxy
    version: 2.1.0

  - name: https://github.com/geerlingguy/ansible-collection-mac.git
    type: git
    version: 4.2.0

  - name: https://github.com/artis3n/ansible-collection-tailscale.git
    type: git
    version: main

roles:
  - name: simoncaron.pve_acme
    scm: git
    src: https://github.com/simoncaron/ansible-role-pve_acme
    version: 1.5.0

  - name: geerlingguy.docker
    scm: git
    src: https://github.com/geerlingguy/ansible-role-docker.git
    version: 7.9.0

  - name: sebdanielsson.cloudflared
    scm: git
    src: https://github.com/sebdanielsson/ansible-role-cloudflared.git
    version: main

  - name: sebdanielsson.xcaddy
    src: https://github.com/sebdanielsson/ansible-role-xcaddy.git
    scm: git
    version: main

  - name: maxhoesel.ddclient
    scm: git
    src: https://github.com/maxhoesel-ansible/ansible-role-ddclient.git
    version: main
